=== Danso28/XML-Lab/dtd/education.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Education (school)+>
<!ATTLIST Education
  xmlns CDATA #FIXED ''>

<!ELEMENT school (name,major,minor,duration)>
<!ATTLIST school
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT major (#PCDATA)>
<!ATTLIST major
  xmlns CDATA #FIXED ''>

<!ELEMENT minor (#PCDATA)>
<!ATTLIST minor
  xmlns CDATA #FIXED ''>

<!ELEMENT duration (#PCDATA)>
<!ATTLIST duration
  xmlns CDATA #FIXED ''>

=== Danso28/XML-Lab/xml/education.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Education SYSTEM "./dtd/education.dtd">
<Education>
  <school>
    <name>Alfred State College - SUNY College of Technology</name>
    <major>Information Technology:Application Software Development(BTech)</major>
    <minor>Information Technology:Web Development</minor>
    <duration>2015 - 2019</duration>
  </school>
  <school>
    <name>Alfred University - NYS College of Ceramics </name>
    <major>Materials Science and Engineering (BS)</major>
    <minor>Physics</minor>
    <duration>2005 - 2010</duration>
  </school>
</Education>
